
spring:
  application:
    name: gateway
  cloud:
    gateway:
      actuator:
        verbose:
          enabled: true
      routes:
        - id: info-service
          uri: lb://info-service #dynamic routing should match the application name
          predicates:
            - Path=/api/info

server:
  port: 8085

eureka:
  client:
    health-check:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

management:
  endpoints:
    enabled-by-default: true
    gateway:
      enabled: true # default value
  web:
    exposure:
      include: '*'

logging:
  level:
    web: DEBUG
    '[net.ttddyy.dsproxy.listener]': debug