info:
  name: "Info Service"
  version: 1
  developer: "@msucil"
  description: "Demo Service to interact with API Gateway"

spring:
  application:
    name: info-service

server:
  port: 8089

eureka:
  client:
    health-check:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

logging:
  level:
    web: DEBUG
    '[net.ttddyy.dsproxy.listener]': debug

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - info
          - health
          - env
          - configprops
          - metrics
          - gateway