
server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # disable self registration as client
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/